server.port: 8085
server.error.include-message: always

logging:
  level:
    root: INFO
    team.caltech.olmago.payment.domain: DEBUG
#    com:
#      querydsl:
#        sql: DEBUG
#    org:
#      hibernate:
#        SQL: DEBUG
#        type: DEBUG

spring:
  jpa:
    show_sql: true
    defer-datasource-initialization: true   # data.sql 자동 실행하려면 스프링부트2.4부터는 반드시 추가해야함
#    format_sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 10

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/payment;
    username: sa
    password:
    #data: classpath:data.sql      지우니까 되네..

  sql:
    init:
      mode: always